aa_js_sql={

"1":"SELECT \n`T0`.`chi_id_utilisateur` , `T0`.`chp_mot_de_passe_utilisateur` , `T0`.`chp_parametres_utilisateur`\n FROM b1.tbl_utilisateurs T0\nWHERE `T0`.`chp_nom_de_connexion_utilisateur` = :nom_de_connexion LIMIT 1 OFFSET 0 ;",
"2":"SELECT \n`T0`.`chi_id_requete` , `T0`.`chp_type_requete` , `T0`.`cht_rev_requete` , `T0`.`cht_sql_requete` , `T0`.`cht_php_requete` , \n`T0`.`cht_commentaire_requete`\n FROM b1.tbl_requetes T0\nWHERE (\/*  *\/ `T0`.`chx_cible_requete` = :T0_chx_cible_requete AND `T0`.`chi_id_requete` = :T0_chi_id_requete AND `T0`.`chp_type_requete` LIKE :T0_chp_type_requete AND `T0`.`cht_rev_requete` LIKE :T0_cht_rev_requete) ORDER BY  `T0`.`chi_id_requete` DESC LIMIT :quantitee OFFSET :debut ;",
"3":"\nUPDATE b1.tbl_requetes SET `chi_id_requete` = :n_chi_id_requete\nWHERE (`chi_id_requete` = :c_chi_id_requete) ;",
"4":"\nDELETE FROM b1.tbl_requetes\nWHERE (`chi_id_requete` = :chi_id_requete AND `chx_cible_requete` = :chx_cible_requete) ;",
"5":"\nDELETE FROM b1.tbl_revs\nWHERE (`chx_cible_rev` = :chx_cible_rev AND `chp_provenance_rev` = :chp_provenance_rev AND `chx_source_rev` = :chx_source_rev) ;",
"6":"SELECT \n`T0`.`chi_id_requete` , `T0`.`cht_sql_requete` , `T0`.`cht_php_requete`\n FROM b1.tbl_requetes T0 ORDER BY  `T0`.`chi_id_requete`  ASC;",
"7":"\nINSERT INTO b1.`tbl_requetes`(\n    `chx_cible_requete` , \n    `chp_type_requete` , \n    `cht_rev_requete` , \n    `cht_sql_requete` , \n    `cht_php_requete`\n) VALUES (\n    :chx_cible_requete , \n    :chp_type_requete , \n    :cht_rev_requete , \n    :cht_sql_requete , \n    :cht_php_requete\n);",
"8":"\nUPDATE b1.tbl_revs SET `chx_source_rev` = :n_chx_source_rev\nWHERE (`chx_cible_rev` = :c_chx_cible_rev AND `chp_provenance_rev` = :c_chp_provenance_rev AND `chx_source_rev` = :c_chx_source_rev) ;",
"9":"\nUPDATE b1.tbl_requetes SET `chp_type_requete` = :n_chp_type_requete , `cht_rev_requete` = :n_cht_rev_requete , `cht_sql_requete` = :n_cht_sql_requete , `cht_php_requete` = :n_cht_php_requete\nWHERE (`chi_id_requete` = :c_chi_id_requete AND `chx_cible_requete` = :c_chx_cible_requete) ;",
"10":"\nUPDATE b1.tbl_bdds SET `chp_rev_travail_basedd` = :n_chp_rev_travail_basedd\nWHERE `chi_id_basedd` = :c_chi_id_basedd ;",
"11":"SELECT \n`T0`.`chi_id_basedd` , `T0`.`chp_rev_travail_basedd` , `T0`.`chp_nom_basedd`\n FROM b1.tbl_bdds T0\nWHERE `T0`.`chi_id_basedd` IN (:les_id_des_bases);",
"12":"\nINSERT INTO b1.`tbl_revs`(\n    `chx_cible_rev` , \n    `chp_provenance_rev` , \n    `chx_source_rev` , \n    `chp_id_rev` , \n    `chp_valeur_rev` , \n    `chp_type_rev` , \n    `chp_niveau_rev` , \n    `chp_quotee_rev` , \n    `chp_pos_premier_rev` , \n    `chp_pos_dernier_rev` , \n    `chp_parent_rev` , \n    `chp_nbr_enfants_rev` , \n    `chp_num_enfant_rev` , \n    `chp_profondeur_rev` , \n    `chp_pos_ouver_parenthese_rev` , \n    `chp_pos_fermer_parenthese_rev` , \n    `chp_commentaire_rev`\n) VALUES (\n    :chx_cible_rev , \n    :chp_provenance_rev , \n    :chx_source_rev , \n    :chp_id_rev , \n    :chp_valeur_rev , \n    :chp_type_rev , \n    :chp_niveau_rev , \n    :chp_quotee_rev , \n    :chp_pos_premier_rev , \n    :chp_pos_dernier_rev , \n    :chp_parent_rev , \n    :chp_nbr_enfants_rev , \n    :chp_num_enfant_rev , \n    :chp_profondeur_rev , \n    :chp_pos_ouver_parenthese_rev , \n    :chp_pos_fermer_parenthese_rev , \n    :chp_commentaire_rev\n);",
"13":"SELECT \n`T0`.`chi_id_rev` , `T0`.`chp_provenance_rev` , `T0`.`chx_source_rev` , `T1`.`chp_nom_source` , `T0`.`chp_valeur_rev` , \n`T0`.`chp_type_rev` , `T0`.`chp_niveau_rev` , `T0`.`chp_pos_premier_rev` , `T0`.`chp_commentaire_rev`\n FROM b1.tbl_revs T0\n LEFT JOIN b1.tbl_sources T1 ON T1.chi_id_source = T0.chx_source_rev\n\nWHERE (`T0`.`chx_cible_rev` = :T0_chx_cible_rev AND `T0`.`chp_provenance_rev` LIKE :T0_chp_provenance_rev AND `T0`.`chx_source_rev` = :T0_chx_source_rev AND `T1`.`chp_nom_source` LIKE :T1_chp_nom_source1 AND `T1`.`chp_nom_source` NOT LIKE :T1_chp_nom_source2 AND `T0`.`chp_valeur_rev` LIKE :T0_chp_valeur_rev AND `T0`.`chp_commentaire_rev` LIKE :T0_chp_commentaire_rev AND `T0`.`chi_id_rev` = :T0_chi_id_rev) ORDER BY  `T0`.`chp_provenance_rev` ASC, `T0`.`chx_source_rev` ASC LIMIT :quantitee OFFSET :debut ;",
"14":"\nDELETE FROM b1.tbl_revs\nWHERE `chx_cible_rev` = :chx_cible_rev ;",
"15":"SELECT \n`T0`.`chi_id_basedd` , `T0`.`chp_nom_basedd` , `T0`.`chp_commentaire_basedd`\n FROM b1.tbl_bdds T0\nWHERE (\/*  *\/ `T0`.`chx_cible_id_basedd` = :T0_chx_cible_id_basedd AND `T0`.`chi_id_basedd` = :T0_chi_id_basedd AND `T0`.`chp_nom_basedd` LIKE :T0_chp_nom_basedd) ORDER BY  `T0`.`chi_id_basedd` ASC LIMIT :quantitee OFFSET :debut ;",
"16":"\nUPDATE b1.tbl_bdds SET `chx_dossier_id_basedd` = :n_chx_dossier_id_basedd , `chp_nom_basedd` = :n_chp_nom_basedd , `chp_rev_basedd` = :n_chp_rev_basedd , `chp_commentaire_basedd` = :n_chp_commentaire_basedd , `chp_genere_basedd` = :n_chp_genere_basedd , `chp_rev_travail_basedd` = :n_chp_rev_travail_basedd , `chp_fournisseur_basedd` = :n_chp_fournisseur_basedd\nWHERE (`chi_id_basedd` = :c_chi_id_basedd AND `chx_cible_id_basedd` = :c_chx_cible_id_basedd) ;",
};